//FAVORITES
export const GET_ALL_FAVORITES = "GET_ALL_FAVORITES"
export const ADD_TO_FAVORITES = "ADD_TO_FAVORITES";
export const REMOVE_FAVORITE = "REMOVE_FAVORITE";

//CHARACTERS
export const GET_ALL_CHARACTERS = "GET_ALL_CHARACTERS"

//EPISODES
export const GET_ALL_EPISODES = "GET_ALL_EPISODES"

//LOCATIONS
export const GET_ALL_LOCATIONS = "GET_ALL_LOCATIONS"

//FILTERS
export const GET_CHARACTER_BY_NAME = "GET_CHARACTER_BY_NAME"
export const SORT = "SORT";
export const FILTER = "FILTER";
export const RESET = "RESET";

//AUTH
export const REGISTER = "REGISTER"
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

//USERS
export const USER_DATA = "USER_DATA";

